policies:
  - Refunds cannot exceed order total.
  - Order cancellation must be requested by the order owner.

domain_rows:
  users:
    - user_id: u_001
      name: Alicia
    - user_id: u_002
      name: Ben
  orders:
    - order_id: o_100
      status: processing
      total: 120.0
    - order_id: o_101
      status: delivered
      total: 55.0

examples:
  - "Example: 'Cancel order o_100 for user u_001' => list_orders -> get_order -> cancel_order"
